# AP 155 Lab Exercise
---
## Exercise 5: Matrices

_Instructions_: 
- **Report figure:** No report figure. Points in the report figure will be allocated to the report discussion 
- **Report discussion:**
  - What were the basis linear equations used to set up the matrix in each question of Problem 2?
  - Once you set up the matrices, what function did you use to solve the matrix equation (Could have different answers)? Check the docstring/documentation/other references and summarize the mechanism behind the function 
- **Code**: Complete the code and ensure it is functional, error-free, readable, and efficient (where needed). Include concise Markdown documentation highlighting the critical steps of your algorithm for each problem.

### Student Information
- _Full Name (Last Name, First Name)_: Lunas, Bryce Enrico
- _Student No._: 2024-01596
- _Section_: THR-TX-X

### Grading Information (c/o Lab Instructor)
- [Rubrics description link](https://drive.google.com/file/d/1BMSlPot2Mc7XLu0eo4S8I8gLBsIadbCL/view?usp=sharing) (Note: percentages may still be tweaked)

| Criteria | Score | Subtotal |
| --- | --- | --- |
| Report figure | XX | 20 |
| Report discussion | XX | 20|
| Code readability | XX | 20 |
| Code efficiency | XX | 20 | 
| Code appropriateness  | XX | 20 | 
| **TOTAL** | XXX | 100 |

_Date and Time Scored (MM/DD/YYYY HH:MM AM/PM):_:_

---
## Section 1: Report

<!-- ### Report figure

<img src="figures/cat.jpg" alt="Alt text" width=45%> <img src="figures/cat.jpg" alt="Alt text" width=45%>


EDIT ME. See instruction above for what to include. Insert caption here, a short description what the figure illustrates. The syntax in markdown for putting a figure is `![Description](local_file_name.png)` or `<img src="/path/to_image.jpg" alt="Alt text" width=45%>`. Make sure the figure has complete elements.
-->

### Report discussion

1. The basis equations come from balancing horizontal and vertical forces to keep the mass still. Horizontally, the leftward force of rope one (negative tension one times cosine of alpha) cancels the rightward force of rope two (tension two times cosine of beta). Vertically, the upward forces of both ropes (tension one times sine of alpha plus tension two times sine of beta) balance gravity (mass times gravity). These two force balances form the matrix equation.

2. We used numpy.linalg.solve to find the unknown rope tensions. Rather than calculating the matrix inverse directly—which can be slow and lead to rounding errors in Python—this function breaks the matrix down into two simpler triangular matrices. It then easily solves for the unknown tensions using basic substitution, making the calculation fast, accurate, and reliable.

### Other comments
I need to practice more coding. I wouldn't be able to finish this activity if I didn't get any help from my classmates.


---
## Section 2: Code

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import math

### Problem 1: (Circuit Analysis)


Consider a long chain of resistors wired up like this:

<img src="reschain.png" alt="Alt text" width=95%>

All the resistors have the same resistance~$R$.  The power rail at the top is at voltage~$V_+=5$V.  The problem is to find the voltages $V_1...V_N$ at the internal points in the circuit.

1. **Using Ohm's law and the Kirchhoff current law**, which says that the total net current flow out of (or into) any junction in a circuit must be zero, show that the voltages $V_1\ldots V_N$ satisfy the equations

$$3V_1 - V_2 - V_3 = V_+ $$
$$-V_1 + 4V_2 - V_3 - V_4 = V_+ $$
      
$$-V_{i-2} - V_{i-1} + 4V_i - V_{i+1} - V_{i+2} = 0 $$

$$-V_{N-3} - V_{N-2} + 4V_{N-1} - V_N = V_- = 0 $$
$$-V_{N-2} - V_{N-1} + 3V_N = V_- = 0 $$

Note: The assignment of $V_-$ is to make the equations symmetric

2. Express these equations in vector form~$A\vec{v} = \vec{w}$ and find the values of the matrix~$A$ and the vector~$\vec{w}$.

3. Write a program to solve for the values of the~$V_i$ when there are $N=6$ internal junctions with unknown voltages.  (Hint: All the values of $V_i$ should lie between zero and $5$V.  If they don't, something is wrong.)

4. Now repeat your calculation for the case where there are $N=10\,000$ internal junctions.  This part is not possible using standard tools like the *solve* function.  You need to make use of the fact that the matrix~$\vec{A}$ is banded.  

### 1.

According to **Kirchhoff's Current Law (KCL)**, the total net current flowing out of junction $V_i$ must equal zero:
$$\sum I_{\text{out}} = 0$$

By **Ohm's Law**, current flowing through a resistor of resistance $R$ from node $i$ to a adjacent node $j$ is:
$$I = \frac{V_i - V_j}{R}$$

For a general internal node $V_i$, it is connected via identical resistors $R$ to four neighbors: $V_{i-2}$, $V_{i-1}$, $V_{i+1}$, and $V_{i+2}$. Setting the sum of currents to zero:

$$\frac{V_i - V_{i-2}}{R} + \frac{V_i - V_{i-1}}{R} + \frac{V_i - V_{i+1}}{R} + \frac{V_i - V_{i+2}}{R} = 0$$

Multiplying the entire equation by $R$:

$$(V_i - V_{i-2}) + (V_i - V_{i-1}) + (V_i - V_{i+1}) + (V_i - V_{i+2}) = 0$$

Combining the $V_i$ terms ($V_i + V_i + V_i + V_i = 4V_i$) and rearranging in index order gives:

$$-V_{i-2} - V_{i-1} + 4V_i - V_{i+1} - V_{i+2} = 0$$

### 2. 

The linear system of equations can be expressed in matrix form $\vec{A}\vec{v} = \vec{w}$, where $\vec{v} = [V_1, V_2, \dots, V_N]^T$ is the vector of unknown junction voltages.

* **Matrix $\vec{A}$ ($N \times N$ pentadiagonal matrix):**

$$\vec{A} = \begin{bmatrix}
 3 & -1 & -1 &  0 &  0 & \dots &  0 &  0 \\
-1 &  4 & -1 & -1 &  0 & \dots &  0 &  0 \\
-1 & -1 &  4 & -1 & -1 & \dots &  0 &  0 \\
 0 & -1 & -1 &  4 & -1 & \dots &  0 &  0 \\
\vdots & & \ddots & \ddots & \ddots & \ddots & & \vdots \\
 0 &  0 & \dots & -1 & -1 &  4 & -1 & -1 \\
 0 &  0 & \dots &  0 & -1 & -1 &  4 & -1 \\
 0 &  0 & \dots &  0 &  0 & -1 & -1 &  3
\end{bmatrix}$$

* **Vector $\vec{w}$ ($N \times 1$ vector):**

$$\vec{w} = \begin{bmatrix} V_+ \\ V_+ \\ 0 \\ \vdots \\ 0 \\ 0 \end{bmatrix} = \begin{bmatrix} 5 \\ 5 \\ 0 \\ \vdots \\ 0 \\ 0 \end{bmatrix}$$


In [5]:
import numpy as np
import matplotlib.pyplot as plt
import math

# Setup parameters
N = 6
V_plus = 5.0  # Volts

# Build matrix A
A = np.zeros((N, N))
for i in range(N):
    A[i, i] = 4
    if i - 1 >= 0: A[i, i - 1] = -1
    if i - 2 >= 0: A[i, i - 2] = -1
    if i + 1 < N: A[i, i + 1] = -1
    if i + 2 < N: A[i, i + 2] = -1

# Boundary conditions
A[0, 0] = 3
A[-1, -1] = 3

# Build vector w
w = np.zeros(N)
w[0] = V_plus
w[1] = V_plus

# Solve A * v = w
v = np.linalg.solve(A, w)

# Display results
print(f"Voltage solutions for N = {N}:")
for i, voltage in enumerate(v, start=1):
    print(f"V_{i} = {voltage:.4f} V")

Voltage solutions for N = 6:
V_1 = 3.7255 V
V_2 = 3.4314 V
V_3 = 2.7451 V
V_4 = 2.2549 V
V_5 = 1.5686 V
V_6 = 1.2745 V


In [24]:
import numpy as np
import matplotlib.pyplot as plt
import math
from scipy.linalg import solve_banded

# Setup parameters
N = 10000
V_plus = 5.0  # Volts

# Matrix A is pentadiagonal (2 diagonals below, 2 diagonals above)
# solve_banded expects array of shape (l + u + 1, N) -> (5, N)
ab = np.zeros((5, N))

ab[0, 2:] = -1   # 2nd super-diagonal
ab[1, 1:] = -1   # 1st super-diagonal
ab[2, :]  =  4   # Main diagonal
ab[3, :-1] = -1  # 1st sub-diagonal
ab[4, :-2] = -1  # 2nd sub-diagonal

# Boundary conditions
ab[2, 0] = 3     # A[0, 0]
ab[2, -1] = 3    # A[N-1, N-1]

# Build vector w
w = np.zeros(N)
w[0] = V_plus
w[1] = V_plus

# Solve linear system
v_10k = solve_banded((2, 2), ab, w)

# Output summary results
print(f"Successfully solved system for N = {N}:")
print(f"First 5 voltages: {v_10k[:5]}")
print(f"Last 5 voltages:  {v_10k[-5:]}")
print(f"All voltages between 0V and 5V: {np.all((v_10k >= 0) & (v_10k <= V_plus))}")

Successfully solved system for N = 10000:
First 5 voltages: [4.99888228 4.99861842 4.99802841 4.99756299 4.99704997]
Last 5 voltages:  [0.00295003 0.00243701 0.00197159 0.00138158 0.00111772]
All voltages between 0V and 5V: True


#### Problem 1 code summary

The purpose of this code is to find the internal voltages across a resistor network by solving the system Av = w. I first set up a standard matrix solver for N = 6 to verify the circuit behavior and ensure all calculated voltages stayed between 0V and 5V. For N=10,000, storing the full matrix uses too much memory, so I used solve_banded from scipy.linalg to solve it efficiently.

---

### Problem 2 (Statics)


Solve the following matrix problems. Set-up the linear equations that describe the problem then solve them 

Part 1: Suppose you have a hanging mass M supported by two ropes (angled by $\alpha$ and $\beta$ with respect to the ceiling). Make a function that calculates the tension on each of the ropes. Put your function in a python file and call it here in the notebook. Check that the answer by computer matches your own computations.


Part 2: 
Masses $m_1, m_2, m_3$, and $m_4$ lie on a $2.00$ [m] beam of negligible mass. They are located $0.20, 0.70, 1.10$, and $1.40$ [m] away from the left end of the beam. Determine the masses $m_1, m_2, m_3$, and $m_4$, given the following constraints: 

- The total mass is $8.00$ [kg]
- If a pivot is placed halfway, the beam will balance if a $1.05$ [kg] mass is placed on the right-end of the beam
- If a pivot is placed $1.20$ [m] away from the right end, then the beam would balance if a $550$ [g] mass is placed on the left end of the beam.
- If the system is split midway, the total mass on the left is $1.00$ [kg] heavier than the total mass on the right

In [22]:
import importlib
import statics_solver

importlib.reload(statics_solver)
from statics_solver import solve_rope_tensions

In [23]:
import numpy as np
from statics_solver import solve_rope_tensions

# Test inputs
M = 10.0          # Mass in kg
alpha_deg = 30.0  # Angle alpha in degrees
beta_deg = 45.0   # Angle beta in degrees
g = 9.81          # Acceleration due to gravity (m/s^2)

# 1. Compute using Python function
T1_num, T2_num = solve_rope_tensions(M, alpha_deg, beta_deg, g)

# 2. Manual/analytical computation
alpha_rad = np.radians(alpha_deg)
beta_rad = np.radians(beta_deg)

T1_analytical = (M * g * np.cos(beta_rad)) / np.sin(alpha_rad + beta_rad)
T2_analytical = (M * g * np.cos(alpha_rad)) / np.sin(alpha_rad + beta_rad)

# Print results
print(f"Numerical solution (Matrix):   T1 = {T1_num:.4f} N, T2 = {T2_num:.4f} N")
print(f"Analytical solution (Formula): T1 = {T1_analytical:.4f} N, T2 = {T2_analytical:.4f} N")

# Verification
np.testing.assert_allclose([T1_num, T2_num], [T1_analytical, T2_analytical], rtol=1e-5)
print("\nSuccess: The computer answer matches manual computations!")

Numerical solution (Matrix):   T1 = 71.8142 N, T2 = 87.9541 N
Analytical solution (Formula): T1 = 71.8142 N, T2 = 87.9541 N

Success: The computer answer matches manual computations!


#### Problem 2 code summary

Include a brief summary (2–3 sentences) at the bottom of your code outlining the purpose of the script and its core algorithm. Focus on explaining why you wrote the code this way and the reasoning behind your implementation choices.

---

#### Problem 2: Part 1 code summary

This code calculates the tensions in two supporting ropes by expressing the static equilibrium equations as a linear matrix system (Ax=b). The function converts the rope angles to radians and uses np.linalg.solve() to quickly compute the tension forces. Writing this logic as a modular function in an external Python file keeps the code reusable, organized, and easy to verify against analytical formulas in the notebook.

----

## Section 3 (Notes)

### Some codes for solving matrix problems

* solving matrix equations ($\bf{A}\vec{x} = \vec{b}$) -> `np.linalg.solve`
* LU-decomposition ($\bf{A} = \bf{L}\bf{U}$) -> `scipy.linalg.lu`
* matrix inversion ($\bf{A}^{-1}$) -> `np.linalg.inv`
* QR-decomposition ($\bf{A} = \bf{Q}\bf{R}$) -> `scipy.linalg.qr`
* eigenvalue problem ($\bf{A}\vec{x} = \lambda \vec{x}$) -> `np.linalg.eig`

Solving matrix problems by themselves isn't difficult. There is an abundance of linear algebra libraries that are ready to use: from the battle-tested ones (the classic [BLAS](https://www.netlib.org/blas/) and [LAPACK](https://www.netlib.org/lapack/)), HPC tools for large problems ([ScaLAPACK](https://netlib.org/scalapack/)), to hardware-accelerated ones often with GPUs ([cuBLAS](https://docs.nvidia.com/cuda/cublas/index.html) and [cuSolver](https://docs.nvidia.com/cuda/cusolver/index.html) for NVIDIA). 

The hardest part is actually composing the matrix. How do you transform a physical problem into a linear algebra problem?

* Circuit: https://personal.math.vt.edu/embree/cmda3606/chapter2.pdf
* Embree [main notes](https://personal.math.vt.edu/embree/cmda3606notes.pdf) + [lab manual](https://personal.math.vt.edu/embree/labman.pdf)

#### Sample Usage (Testing different codes)

In [2]:
A = np.array([[1,0,2],[-2,-1,3],[0,3,5]])
B = np.array([[-2],[1],[-3]])


In [3]:
sigma_z = [[1,0],[0,-1]]
sigma_y = [[0,-1j],[1j,0]]
sigma_x = [[0,1],[1,0]]

In [4]:
ans = np.linalg.solve(sigma_x, sigma_y)
ans = np.linalg.inv(A) @ B


In [5]:
from scipy.linalg import *
p, l, u = lu(A)
p, l, u

(array([[0., 0., 1.],
        [1., 0., 0.],
        [0., 1., 0.]]),
 array([[ 1.        ,  0.        ,  0.        ],
        [-0.        ,  1.        ,  0.        ],
        [-0.5       , -0.16666667,  1.        ]]),
 array([[-2.        , -1.        ,  3.        ],
        [ 0.        ,  3.        ,  5.        ],
        [ 0.        ,  0.        ,  4.33333333]]))

### Importing functions from a python file

In [6]:
import samplePackage as sP

In [9]:
testMat = sP.createZerosArray(4,5)

In [13]:
testMat[1] = [1,2,3,4,5]

In [14]:
testMat

array([[0., 0., 0., 0., 0.],
       [1., 2., 3., 4., 5.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### np.roll

In [19]:
## Useful tips. Not required to solve the problems below!

# Suppose you have a Numpy array
x = np.zeros((4,4))
x[1,2] = 5
for row in x:
    print(row)

#rint(x[0,1:3])


# I can move all values to the left/right using roll
x_roll = np.roll(x, 1) # change 1 to -1, what happens? 
#x_roll2 = np.roll(x, -1)
print(x_roll)

x_roll2 = np.roll(x, 2)
print(x_roll2)

[0. 0. 0. 0.]
[0. 0. 5. 0.]
[0. 0. 0. 0.]
[0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 5.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [5. 0. 0. 0.]
 [0. 0. 0. 0.]]
